final List<String> jobOptions = [
  'Galian',
  'Pemasangan Kabel',
  'Pengecoran',
  'Testing',
  'Instalasi Tiang',
  'Pemasangan Panel',
  'Uji Fungsi',
  'Pemasangan Trafo',
  'Pemasangan Jaringan',
  'Pemasangan Meteran',
  'Pemasangan Grounding',
  'Pemasangan Box',
  'Pemasangan KWH Meter',
  'Pemasangan JTR',
  'Pemasangan JTM',
];
